### ISSUE TITLE
RTT Questions

### ISSUE THREAD

**Issue by SterlingButters** [nospaceships/node-net-ping#60]
When you say that the results are not 100% accurate, how does this differ from the Unix ping command? 

Are you saying that, in general, ping results should not be considered 100% accurate or specifically in your package?

Also is there a way to increase the precision of the RTT in milliseconds since it is just a `Date` instance? Perhaps to the same resolution as the Unix command i.e. `time=0.050 ms`?

**Comment by stephenwvickers** [comment]
Hi @SterlingButters 

You could say it is no different, in that ping is at the mercy of the kernel using an appropriate scheduling mechanism to give a consistent response time.

The issue is that (in my experience) in node.js it isn't consistent, specifically under very high load, or using large data structures, where garbage collection causes pauses in program execution, resulting in inaccurate response times if you are wanting to track down to the millisecond.

The start sent and received timestamps passed to the various callbacks are `Date` instances, so they are already at millisecond precision.

Steve
